apiVersion: v1
kind: ConfigMap
metadata:
  name: postgre-configmap-env
  # namespace: lazy-stock-screener
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: customer-db
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: customer-postgres-sts
  # namespace: lazy-stock-screener
  labels:
    app.kubernetes.io/name: customer-postgres-sts
    app.kubernetes.io/component: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lazy-stock-screener
      component: customer-postgres
      tier: postgres
  serviceName: "customer-postgres"
  template:
    metadata:
      labels:
        app: lazy-stock-screener
        component: customer-postgres
        tier: postgres
    spec:
      containers:
        - name: customer-postgres
          image: postgres:10
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: postgre-configmap-env
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: customer-postgre-pvc
              mountPath: /var/lib/postgresql
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: customer-postgre-pvc
        # namespace: lazy-stock-screener
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi





