apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Values.global.config.namespace }}
data:
  PORT: "{{ .Values.deployment.containerPort }}"
  STOCK_DEV_VER: "v1"
  STOCK_DEV_HOST: "http://localhost"
  STOCK_DEV_PORT: "5000"
  STOCK_PROD_VER: "{{ .Values.api.stock.ver }}"
  STOCK_PROD_HOST: "{{ .Values.api.stock.host }}"
  STOCK_PROD_PORT: "{{ .Values.api.stock.port }}"