apiVersion: v1
kind: Service
metadata:
  name: customer-web-service
  namespace: lazy-stock-screener
  labels:
    app.kubernetes.io/name: customer-web-service
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app: customer-web
  ports:
    - name: http
      port: 3000
      targetPort: 8080
