apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: lazy-stock-screener-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
  - port:
      name: https-default
      number: 443
      protocol: HTTPS
    hosts:
      - '*'
    tls:
      credentialName: ingress-cert # this should match with Certificate secretName
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds