apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lazy-stock-screener-virtual-service
  namespace: lazy-stock-screener
spec:
  # tolerations:
  #   - key: mgt-host
  #     operator: Equal
  #     value: "true"
  #     effect: NoSchedule
  hosts:
    - "*"
  gateways:
    - istio-system/lazy-stock-screener-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 3000
            host: customer-web-service
