apiVersion: v1
kind: Service
metadata:
  name: customer-postgre-service
  # namespace: lazy-stock-screener
  labels:
    app.kubernetes.io/name: customer-postgre-service
    app.kubernetes.io/component: customer
spec:
  clusterIP: None
  selector:
    app: lazy-stock-screener
    component: customer-postgres
    tier: postgres
  ports:
    - name: http
      port: 5432
      targetPort: 5432
