apiVersion: v1
kind: Service
metadata:
  name: identity-redis-service
  # namespace: lazy-stock-screener
  labels:
    app.kubernetes.io/name: identity-redis-service
    app.kubernetes.io/component: identity
spec:
  clusterIP: None
  selector:
    app: lazy-stock-screener
    component: identity-redis
    tier: redis      
  ports:
    - name: http
      port: 6379
      targetPort: 6379
