apiVersion: v1
kind: Service
metadata:
  name: stock-server-service
  # namespace: lazy-stock-screener
  # labels:
  #   app.kubernetes.io/name: stock-service
  #   app.kubernetes.io/component: stock
spec:
  type: ClusterIP
  selector:
    app: lazy-stock-screener
    component: stock-server
    tier: golang     
  ports:
    - name: http
      port: 5000
      targetPort: 80
