apiVersion: v1
kind: Service
metadata:
  name: stock-mongo-service
  # namespace: lazy-stock-screener
  labels:
    app.kubernetes.io/name: stock-mongo-service
    app.kubernetes.io/component: stock
spec:
  clusterIP: None
  selector:
    app: lazy-stock-screener
    component: stock-mongo
    tier: mongo  
  ports:
    - name: http
      port: 27017
      targetPort: 27017
