apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-web-configmap
  # namespace: lazy-stock-screener
data:
  PORT: "8080"
  HOST: "0.0.0.0"
  STOCK_DEV_VER: "v1"
  STOCK_DEV_HOST: "http://localhost"
  STOCK_DEV_PORT: "80"
  STOCK_PROD_VER: "v1"
  STOCK_PROD_HOST: "http://localhost"
  STOCK_PROD_PORT: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-web-deployment
  # namespace: lazy-stock-screener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lazy-stock-screener
      component: customer-web
      tier: react
  template:
    metadata:
      labels:
        app: lazy-stock-screener
        component: customer-web
        tier: react 
    spec:
      containers:
        - name: customer-web
          image: customer-web
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: customer-web-configmap
